_target_: src.datamodules.imagenet.ImagenetDataModule
data_dir: /home/user/datasets/imagenet
image_size: 224
batch_size: 8  # per GPU
batch_size_eval: ${eval:${.batch_size} * 2}
num_workers: 32  # For preprocessing only
shuffle: True
pin_memory: True
